# Generated by Django 3.2.9 on 2021-11-07 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='APIStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_at', models.DateTimeField(auto_now=True)),
                ('response_time', models.DecimalField(db_index=True, decimal_places=8, max_digits=10)),
            ],
        ),
    ]
