# Generated by Django 3.2.9 on 2021-11-07 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apistat',
            name='response_time',
            field=models.DecimalField(db_index=True, decimal_places=7, max_digits=9),
        ),
    ]
