# Generated by Django 3.2.9 on 2021-11-06 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VMTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='VirtualMachine',
            fields=[
                ('vm_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('tags', models.ManyToManyField(blank=True, related_name='virtual_machines', to='cloud.VMTag')),
            ],
        ),
        migrations.CreateModel(
            name='CloudFirewallRule',
            fields=[
                ('fw_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('dest_tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dest_rules', to='cloud.vmtag')),
                ('source_tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_rules', to='cloud.vmtag')),
            ],
        ),
    ]
